apiVersion: v1
kind: Service
metadata:
  name: event-ingestion
  namespace: ai-personalization-platform
spec:
  selector:
    app: event-ingestion
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
