#!/usr/bin/env python3
"""
Regenerates the Claude Code Skills section in README.md from SKILL.md frontmatter.

The section in README.md must be wrapped in marker comments:
    <!-- CLAUDE-SKILLS:START -->
    ...generated content — do not edit manually...
    <!-- CLAUDE-SKILLS:END -->

Usage:
    python scripts/sync-readme-skills.py           # update README.md in place
    python scripts/sync-readme-skills.py --check   # exit 1 if README is out of sync (for CI)
    python scripts/sync-readme-skills.py --dry-run # print generated section, don't write

The script reads name, description, and category from each SKILL.md frontmatter.
Categories: workflow | infrastructure | learning | tooling
Add new skills by dropping a SKILL.md with those three fields — README updates automatically.
"""

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
SKILLS_DIR = REPO_ROOT / ".claude" / "skills"
README_PATH = REPO_ROOT / "README.md"

START_MARKER = "<!-- CLAUDE-SKILLS:START -->"
END_MARKER = "<!-- CLAUDE-SKILLS:END -->"

CATEGORY_ORDER = ["workflow", "infrastructure", "learning", "tooling"]
CATEGORY_TITLES = {
    "workflow":       "Development Workflow",
    "infrastructure": "Infrastructure",
    "learning":       "Learning",
    "tooling":        "Tooling",
}
CATEGORY_INTROS = {
    "workflow": (
        "Skills that cover the full feature lifecycle — "
        "from branch creation to pull request."
    ),
    "infrastructure": (
        "Skills for managing and validating the local infrastructure stack."
    ),
    "learning": (
        "Skills that embed active learning into the build process, "
        "anchored to *Designing Data-Intensive Applications* (Kleppmann)."
    ),
    "tooling": (
        "Skills for maintaining repo structure, context, and documentation."
    ),
}


def parse_frontmatter(path: Path) -> dict:
    """Extract name, description, and category from SKILL.md YAML frontmatter."""
    content = path.read_text()
    match = re.match(r"^---\n(.*?)\n---", content, re.DOTALL)
    if not match:
        return {}
    fm = {}
    for line in match.group(1).splitlines():
        if ": " in line:
            key, _, value = line.partition(": ")
            fm[key.strip()] = value.strip()
    return fm


def collect_skills() -> dict[str, list[dict]]:
    """Read all SKILL.md files and group by category."""
    by_category: dict[str, list[dict]] = {c: [] for c in CATEGORY_ORDER}
    for skill_dir in sorted(SKILLS_DIR.iterdir()):
        skill_file = skill_dir / "SKILL.md"
        if not skill_file.exists():
            continue
        fm = parse_frontmatter(skill_file)
        name = fm.get("name", "")
        description = fm.get("description", "")
        category = fm.get("category", "tooling")
        if not name or not description:
            print(f"  ⚠ Skipping {skill_dir.name}: missing name or description", file=sys.stderr)
            continue
        if category not in by_category:
            by_category[category] = []
        # Truncate description at first sentence for the table
        short_desc = description.split(". ")[0].rstrip(".")
        by_category[category].append({"name": name, "short_desc": short_desc})
    return by_category


def build_skills_section(by_category: dict[str, list[dict]]) -> str:
    """Generate the full skills section as a markdown string."""
    lines = [
        "<!-- CLAUDE-SKILLS:START -->",
        "<!-- Auto-generated by scripts/sync-readme-skills.py — do not edit manually -->",
        "",
        "## Claude Code Integration",
        "",
        "This project is built with [Claude Code](https://claude.ai/code) as an active "
        "development partner. Custom skills automate the full development lifecycle and "
        "embed active learning into every step of the build.",
        "",
    ]

    for category in CATEGORY_ORDER:
        skills = by_category.get(category, [])
        if not skills:
            continue
        title = CATEGORY_TITLES[category]
        intro = CATEGORY_INTROS[category]
        lines += [
            f"### {title}",
            "",
            intro,
            "",
            "| Skill | Purpose |",
            "|---|---|",
        ]
        for skill in skills:
            lines.append(f"| **`/{skill['name']}`** | {skill['short_desc']} |")
        lines.append("")

    # Anki export note — always shown if learning skills exist
    if by_category.get("learning"):
        lines += [
            "Concept quiz results can be exported to Anki for spaced repetition review:",
            "",
            "```bash",
            "python scripts/export-anki.py                  # all services",
            "python scripts/export-anki.py --missed-only    # weak-area focus deck",
            "```",
            "",
        ]

    # Context system layout
    lines += [
        "### Context System",
        "",
        "The repo uses a graph-aware context system so Claude loads only the minimum "
        "context needed per task.",
        "",
        "```",
        "_master.md                          ← service relationship graph",
        "services/<name>/CONTEXT.md          ← living context doc per service",
        "docs/decisions/                     ← ADRs + retrospectives",
        "docs/incidents/                     ← incident log",
        "docs/sys-design-concepts/           ← concept quiz history per service",
        "```",
        "",
        "After every task: `scripts/update-context.sh <service-name>`",
        "",
        "<!-- CLAUDE-SKILLS:END -->",
    ]
    return "\n".join(lines)


def update_readme(new_section: str, dry_run: bool = False, check: bool = False) -> bool:
    """
    Replace the content between markers in README.md.
    Returns True if README was (or would be) changed.
    """
    readme = README_PATH.read_text()

    start_idx = readme.find(START_MARKER)
    end_idx = readme.find(END_MARKER)

    if start_idx == -1 or end_idx == -1:
        print(
            f"Error: markers not found in {README_PATH}.\n"
            f"Add these to README.md where the skills section should appear:\n\n"
            f"  {START_MARKER}\n  {END_MARKER}",
            file=sys.stderr,
        )
        sys.exit(1)

    end_idx += len(END_MARKER)
    current_section = readme[start_idx:end_idx]
    changed = current_section.strip() != new_section.strip()

    if dry_run:
        print(new_section)
        return changed

    if check:
        if changed:
            print(
                "✗ README.md skills section is out of sync with .claude/skills/.\n"
                "  Run: python scripts/sync-readme-skills.py",
                file=sys.stderr,
            )
            return True
        print("✓ README.md skills section is up to date.")
        return False

    if not changed:
        print("✓ README.md already up to date — no changes needed.")
        return False

    updated_readme = readme[:start_idx] + new_section + readme[end_idx:]
    README_PATH.write_text(updated_readme)
    print(f"✓ README.md updated.")
    return True


def main():
    parser = argparse.ArgumentParser(description=__doc__.strip())
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if README is out of sync (for CI)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print generated section without writing")
    args = parser.parse_args()

    print("Scanning skills...")
    by_category = collect_skills()
    total = sum(len(v) for v in by_category.values())
    for cat, skills in by_category.items():
        if skills:
            print(f"  {CATEGORY_TITLES[cat]}: {', '.join(s['name'] for s in skills)}")
    print(f"  Total: {total} skills\n")

    new_section = build_skills_section(by_category)
    changed = update_readme(new_section, dry_run=args.dry_run, check=args.check)

    if args.check and changed:
        sys.exit(1)


if __name__ == "__main__":
    main()
